/**
 * Central string table. Voice: "dry with light personality" per D-22.
 * Short, observational, one turn of personality, no exclamation marks (unless ironic), no emoji.
 * Errors state what happened and the implied next step. Nothing else.
 */

export const COPY = {
  auth: {
    signIn: {
      title: 'Welcome back',
      subtitle: 'Sign in and get on with it.',
      emailLabel: 'Email',
      emailPlaceholder: 'you@example.com',
      passwordLabel: 'Password',
      passwordPlaceholder: '••••••••',
      submit: 'Sign in',
      genericError: 'Sign in failed. Try again.',
      footerPrompt: 'No account yet?',
      footerAction: 'Create one',
    },
    signUp: {
      title: 'Create account',
      subtitle: 'Track your intake across devices.',
      emailLabel: 'Email',
      emailPlaceholder: 'you@example.com',
      passwordLabel: 'Password',
      passwordPlaceholder: 'at least 6 characters',
      submit: 'Create account',
      success: 'Account created. Check your email if confirmation is required, then sign in.',
      genericError: 'Sign up failed. Try again.',
      footerPrompt: 'Already have an account?',
      footerAction: 'Sign in',
    },
    validation: {
      required: 'Required',
      invalidEmail: 'Not a valid email',
      shortPassword: 'At least 6 characters',
    },
  },

  today: {
    heading: 'Today',
    sectionMeals: 'Meals',
    emptyEntries: 'An empty log. What a glorious, untouched canvas.',
    fabLabel: 'Log a meal',
    deleteFailedTitle: "Couldn't delete meal.",
  },

  history: {
    heading: 'History',
    legendAtGoal: 'At goal',
    legendUnder: 'Under',
    legendOver: 'Over',
    jumpToToday: 'Jump to today',
    prevMonth: 'Previous month',
    nextMonth: 'Next month',
    emptyDay: 'Nothing logged that day.',
    detailClose: 'Close',
    detailCaloriesLabel: 'Calories',
    mealsSingular: 'meal',
    mealsPlural: 'meals',
  },

  profile: {
    heading: 'Profile',
    subtitle: 'Daily nutrition goals',
    sectionWeight: 'Weight',
    logWeightButton: 'Log weight',
    sectionSession: 'Session',
    openLibraryWithCount: (n: number) => `Food library (${n})`,
    openLibrary: 'Food library',
    goals: {
      calorieLabel: 'Calorie goal',
      caloriePlaceholder: '2000',
      proteinLabel: 'Protein goal (g)',
      carbsLabel: 'Carbs goal (g)',
      fatLabel: 'Fat goal (g)',
      optionalPlaceholder: 'optional',
      saveButton: 'Save goals',
      saved: 'Goals saved.',
      saveFailedTitle: "Couldn't save goals.",
      required: 'Calorie goal is required',
      mustBePositive: 'Must be a positive number',
      mustBeNonNegative: 'Must be ≥ 0',
    },
    weight: {
      sheetTitle: 'Log weight',
      weightLabel: 'Weight (kg)',
      weightPlaceholder: 'e.g. 72.4',
      bodyFatLabel: 'Body fat % (optional)',
      bodyFatPlaceholder: '—',
      saveButton: 'Save weight',
      saveFailedTitle: "Couldn't save weight.",
      chartEmptyTitle: 'No weight logged yet.',
      chartEmptyHint: 'Log one to start a trend.',
      required: 'Weight is required',
      mustBePositive: 'Must be a positive number',
      mustBeRealistic: 'Must be realistic',
      bodyFatRange: 'Must be between 0 and 100',
    },
    dangerZone: {
      signOutButton: 'Sign out',
      signOutTitle: 'Sign out?',
      signOutBody: 'Your data stays on the server.',
      signOutConfirm: 'Sign out',
      signOutCancel: 'Cancel',
      signOutFailedTitle: "Couldn't sign out.",
    },
  },

  foods: {
    library: {
      title: 'Foods',
      closeLabel: 'Close food library',
      closeAction: 'Close',
      addLabel: 'Add food',
      addAction: 'Add',
      scanLabel: 'Scan a barcode',
      scanAction: 'Scan',
      searchLabel: 'Search',
      searchPlaceholder: 'Find a food',
      emptyLibrary: 'An empty library. Tap Add to put something in it.',
      emptySearch: 'No match.',
    },
    new: {
      title: 'New food',
    },
    edit: {
      title: 'Edit food',
      missing: "That food isn't in your library.",
    },
    form: {
      nameLabel: 'Name',
      namePlaceholder: 'e.g. Chicken breast',
      servingLabel: 'Serving size',
      servingPlaceholder: 'e.g. 100 g, 1 cup',
      kcalLabel: 'Calories per serving',
      kcalPlaceholder: '0',
      proteinLabel: 'Protein (g)',
      carbsLabel: 'Carbs (g)',
      fatLabel: 'Fat (g)',
      macroPlaceholder: '—',
      saveNew: 'Save food',
      saveEdit: 'Save changes',
      deleteButton: 'Delete food',
      deleteConfirmTitle: 'Delete food?',
      deleteConfirmBody: (name: string) => `Remove "${name}" from your library.`,
      deleteConfirmCancel: 'Cancel',
      deleteConfirmAction: 'Delete',
      saveFailedTitle: "Couldn't save food.",
      updateFailedTitle: "Couldn't update food.",
      deleteFailedTitle: "Couldn't delete food.",
      editLabel: (name: string) => `Edit ${name}`,
      nameRequired: 'Name is required',
      kcalRequired: 'Calories per serving is required',
      mustBePositive: 'Must be a positive number',
      mustBeNonNegative: 'Must be ≥ 0',
      sanityMildPrefix: 'Numbers look off',
      sanityBlatantPrefix: "These macros don't add up",
      sanityImplied: (kcal: number) => `Implied ${kcal} kcal from macros.`,
    },
  },

  log: {
    sheet: {
      titleAdd: 'Log meal',
      titleEdit: 'Edit meal',
      cancel: 'Cancel',
      tabLog: 'Log',
      tabQuick: 'Quick add',
      saveFailedTitle: "Couldn't save meal.",
      updateFailedTitle: "Couldn't update meal.",
    },
    quickAdd: {
      nameLabel: 'Name',
      namePlaceholder: 'e.g. Chicken bowl',
      caloriesLabel: 'Calories',
      caloriesPlaceholder: '0',
      proteinLabel: 'Protein (g)',
      carbsLabel: 'Carbs (g)',
      fatLabel: 'Fat (g)',
      macroPlaceholder: '—',
      saveNew: 'Save meal',
      saveEdit: 'Save changes',
      saving: 'Saving.',
      nameRequired: 'Name is required',
      caloriesRequired: 'Calories required',
      mustBePositive: 'Must be a positive number',
      mustBeNonNegative: 'Must be ≥ 0',
    },
    search: {
      placeholder: 'Search foods',
      sectionRecents: 'Recents',
      sectionLibrary: 'Your library',
      sectionUsda: 'USDA',
      emptyRecents: 'Nothing yet. Search for a food to log your first meal.',
      emptyUsda: 'No matches.',
      attribution: 'Search powered by USDA FoodData Central',
      perServing: 'per serving',
      oneServing: '1 serving',
      searchFailedFallback: 'Search failed. Try again.',
    },
    selected: {
      back: '\u2190 Back to results',
      backLabel: 'Back to results',
      servings: 'Servings',
      logging: "You're logging",
      logButton: 'Log meal',
      saving: 'Saving.',
      perServingPrefix: 'Per serving:',
    },
  },

  entries: {
    defaultEmpty: 'No meals yet.',
    deleteLabel: (name: string) => `Delete ${name}`,
    editLabel: (name: string) => `Edit ${name}`,
    deleteButton: 'Delete',
    badgeLabel: "Macros don't match calories",
  },

  stepper: {
    decrease: 'Decrease servings',
    increase: 'Increase servings',
    valueLabel: (formatted: string) => `Servings: ${formatted}. Tap to edit.`,
  },

  totals: {
    todayLabel: 'Calories today',
    over: (n: number) => `${n} over.`,
    remaining: (n: number) => `${n} kcal left.`,
    proteinLabel: 'Protein',
    carbsLabel: 'Carbs',
    fatLabel: 'Fat',
  },

  barcode: {
    screenTitle: 'Scan barcode',
    closeLabel: 'Close scanner',
    permissionPending: 'Asking for camera access.',
    permissionDenied: 'Camera access denied. You can enter the barcode by hand.',
    grantButton: 'Allow camera',
    overlayHint: 'Line up a barcode.',
    manualLink: 'Enter barcode manually',
    manualTitle: 'Enter barcode',
    manualPlaceholder: 'e.g. 3017620422003',
    manualSubmit: 'Look up',
    manualInvalid: 'Enter a numeric barcode (8 to 14 digits).',
    lookingUp: (code: string) => `Looking up ${code}.`,
    noMatch: 'No match for this barcode.',
    fallbackToManual: 'Enter macros by hand',
    lookupFailed: "Couldn't reach the lookup service. Try again.",
    retry: 'Try again',
  },

  errors: {
    network: "Couldn't reach the server. Try again in a moment.",
    unauthorized: 'Session expired. Sign in again.',
    unknown: 'Something went wrong. Try again.',
    notSignedIn: 'Not signed in.',
    missingEnv:
      'Missing Supabase env vars. Set EXPO_PUBLIC_SUPABASE_URL and EXPO_PUBLIC_SUPABASE_ANON_KEY in .env (see .env.example).',
  },
} as const;

export type Copy = typeof COPY;
